import { images } from './constants/index'

export const models = [
  /* Parts */

  {
    title: 'Head Piston',
    description: 'The Head Piston of a single cylinder engine.',
    software: 'Solidworks',
    pictures: [
      images.solidworks__1,
      images.solidworks__2,
      images.solidworks__3,
      images.solidworks__4,
    ],
    file: 'Head__Piston.SLDPRT',
    category: 'part',
    link: 'head-piston',
  },
  {
    title: 'Connect Rod',
    description: 'The connecting rod of a cylinder engine.',
    software: 'Solidworks',
    pictures: [
      images.connectRod__1,
      images.connectRod__2,
      images.connectRod__3,
      images.connectRod__4,
    ],
    file: 'Connecting__Rod.SLDPRT',
    category: 'part',
    link: 'connect-rod',
  },
  {
    title: 'Connect Rod Cover',
    description: 'The cover of the connect rod.',
    software: 'Solidworks',
    pictures: [
      images.connectRodCover__1,
      images.connectRodCover__2,
      images.connectRodCover__1,
      images.connectRodCover__2,
    ],
    file: 'Connecting__RodCover.SLDPRT',
    category: 'part',
    link: 'connect-rod-cover',
  },
  {
    title: 'Crank Shaft',
    description: 'Single cylinder engine crank shaft.',
    software: 'Solidworks',
    pictures: [
      images.CrankShaft__1,
      images.CrankShaft__2,
      images.CrankShaft__3,
      images.CrankShaft__4,
    ],
    file: 'Crankshaft.SLDPRT',
    category: 'part',
    link: 'crank-shaft',
  },
  {
    title: 'Item 5',
    description: 'This is a description for the part 5',
    software: 'Solidworks',
    pictures: [
      images.solidworks__1,
      images.solidworks__2,
      images.solidworks__3,
      images.solidworks__4,
    ],
    file: 'test.txt',
    category: 'part',
    link: 'item-5',
  },
  {
    title: 'Item 6',
    description: 'This is a description for the part 6',
    software: 'Catia',
    pictures: [
      images.catia__1,
      images.catia__2,
      images.catia__3,
      images.catia__4,
    ],
    file: 'test.txt',
    category: 'part',
    link: 'item-6',
  },
  {
    title: 'Item 7',
    description: 'This is a description for the part 7',
    software: 'AutoCad',
    pictures: [
      images.autocad__1,
      images.autocad__2,
      images.autocad__1,
      images.autocad__2,
    ],
    file: 'test.txt',
    category: 'part',
    link: 'item-7',
  },
  {
    title: 'Item 8',
    description: 'This is a description for the part 8',
    software: 'Fusion',
    pictures: [
      images.fusion__1,
      images.fusion__1,
      images.fusion__1,
      images.fusion,
    ],
    file: 'test.txt',
    category: 'part',
    link: 'item-8',
  },

  /* Drawings */

  {
    title: 'Item 9',
    description: 'This is a description for the drawing 9',
    software: 'Solidworks',
    pictures: [
      images.solidworks__1,
      images.solidworks__2,
      images.solidworks__3,
      images.solidworks__4,
    ],
    file: 'test.txt',
    category: 'drawing',
    link: 'item-9',
  },
  {
    title: 'Item 10',
    description: 'This is a description for the drawing 10',
    software: 'AutoCad',
    pictures: [
      images.autocad__1,
      images.autocad__2,
      images.autocad__1,
      images.autocad__2,
    ],
    file: 'test.txt',
    category: 'drawing',
    link: 'item-10',
  },
  {
    title: 'Item 11',
    description: 'This is a description for the drawing 11',
    software: 'Fusion',
    pictures: [
      images.fusion__1,
      images.fusion__1,
      images.fusion__1,
      images.fusion,
    ],
    file: 'test.txt',
    category: 'drawing',
    link: 'item-11',
  },
  {
    title: 'Item 12',
    description: 'This is a description for the drawing 12',
    software: 'Catia',
    pictures: [
      images.catia__1,
      images.catia__2,
      images.catia__3,
      images.catia__4,
    ],
    file: 'test.txt',
    category: 'drawing',
    link: 'item-12',
  },
  {
    title: 'Item 13',
    description: 'This is a description for the drawing 13',
    software: 'AutoCad',
    pictures: [
      images.autocad__1,
      images.autocad__2,
      images.autocad__1,
      images.autocad__2,
    ],
    file: 'test.txt',
    category: 'drawing',
    link: 'item-13',
  },
  {
    title: 'Item 14',
    description: 'This is a description for the drawing 14',
    software: 'Fusion',
    pictures: [
      images.fusion__1,
      images.fusion__1,
      images.fusion__1,
      images.fusion,
    ],
    file: 'test.txt',
    category: 'drawing',
    link: 'item-14',
  },

  /* Assemblies */

  {
    title: 'Item 15',
    description: 'This is a description for the assembly 15',
    software: 'Solidworks',
    pictures: [
      images.solidworks__1,
      images.solidworks__2,
      images.solidworks__3,
      images.solidworks__4,
    ],
    file: 'test.txt',
    category: 'assembly',
    link: 'item-15',
  },
  {
    title: 'Item 16',
    description: 'This is a description for the assembly 16',
    software: 'Catia',
    pictures: [
      images.autocad__1,
      images.autocad__2,
      images.autocad__1,
      images.autocad__2,
    ],
    file: 'test.txt',
    category: 'assembly',
    link: 'item-16',
  },
  {
    title: 'Item 17',
    description: 'This is a description for the assembly 17',
    software: 'Fusion',
    pictures: [
      images.fusion__1,
      images.fusion__1,
      images.fusion__1,
      images.fusion,
    ],
    file: 'test.txt',
    category: 'assembly',
    link: 'item-17',
  },
]
